# Generated by Django 5.0.6 on 2024-08-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_dorminspect_blbzj_alter_dorminspect_blct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorminspect',
            name='score',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
