# Generated by Django 5.0.6 on 2024-08-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_dorminspect_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorminspect',
            name='score',
        ),
    ]
