# Generated by Django 5.0.6 on 2024-08-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_dorminspect_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorminspect',
            name='score',
            field=models.IntegerField(blank=True, default=9, editable=False, null=True),
        ),
    ]
