# Generated by Django 5.0.6 on 2024-08-07 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_dorminspect_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorminspect',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
