# Generated by Django 5.0.6 on 2024-08-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_dorminspect_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorminspect',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=3, default=9.0, editable=False, max_digits=10, null=True),
        ),
    ]
